name: schedule2
on:
  schedule:
    - cron: "* * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "IS_FORK=$(curl "$GITHUB_API_URL/repos/$GITHUB_REPOSITORY" | jq -r .fork)" >> $GITHUB_ENV
      - if: env.IS_FORK == 'false'
        uses: hmarr/debug-action@v2
      - if: env.IS_FORK == 'true'
        run: echo "forked repo!"
